version: "3.8"
services:
  meli-front:
    image: nicohnavarro/meli-front
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - "meli-app"
  meli-back:
    image: nicohnavarro/meli-back
    ports:
      - "4000:4000"
    networks:
      - "meli-app"
networks:
  meli-app:
    driver: bridge